Documentation:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/EmptyLinesAroundAccessModifier:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/IndentationConsistency:
  EnforcedStyle: rails
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/GuardClause:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/SymbolArray:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/Delegate:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
