AllCops:
  Exclude:
    - "**/*.erb"
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Lint/SuppressedException:
  Enabled: false
Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - concerning
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Performance/Casecmp:
  Enabled: false
Rails/Delegate:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/Output:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/LambdaCall:
  Exclude:
    - '**/*.jbuilder'
Style/Next:
  MinBodyLength: 20
Style/NumericPredicate:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
