ClassAndModuleChildren:
  Enabled: false
Documentation:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Rails/Delegate:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/Output:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/AsciiComments:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/EmptyLinesAroundAccessModifier:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/IndentationConsistency:
  EnforcedStyle: rails
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/NumericPredicate:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
